### PR TITLE
Make reporter a no-op when not on AppVeyor

### PR DESCRIPTION
**Pull request by guidobouman**
Oopsies, I broke the reporter for local test runs. 😅

This PR does the same thing without breaking local builds. (And I've tested this a bit better.)

### CODE REVIEW

**Comment by guidobouman** [comment]
@bryanwood You might want to look at this. 😅

**Comment by bryanwood** [comment]
Not going to be able to release this one for about 48 hours most likely, on phone with no laptop. Sorry about that!

**Comment by bryanwood** [comment]
I've sent a collaborator invite on GitHub, if you want to do a release just need to bump the package.json version in a new commit and run npm publish (will need to know npm username to add as a collaborator there).

**Comment by guidobouman** [comment]
Hey Bryan,

Thanks for the invite. My npm username is `guidobouman` just like here.

**Comment by bryanwood** [comment]
I've added you to the npm package.

**Comment by guidobouman** [comment]
Published v0.4.1!

**Pull request merged**
