### PR TITLE
Only publish reporter when on AppVeyor.

### PR DESCRIPTION
**Pull request by guidobouman**
When running this reporter on the command-line, all requests time out. Resulting in a delay of about a minute each time tests are run.

### CODE REVIEW

**Comment by guidobouman** [comment]
@bryanwood Planning on looking at this? Or is this repo abandoned?

**Comment by guidobouman** [comment]
Woohoo! 🎉 If this is releasing anytime we would be greatly helped! 😁

**Comment by bryanwood** [comment]
Heya!

I missed the notification for this entirely, sorry about that.

I've published as `0.4.0`.

Let me know if you'd like commit and publish access to this :)

**Comment by guidobouman** [comment]
Thanks man!

That's fine, I think. =] It works nicely otherwise!

**Pull request merged**
